site_name: Hydrogen Proxy

nav:
  - Hydrogen:
    - index.md
    - How it works: how-it-works.md
    - Limitations: limitations.md

extra:
  homepage: /
  status:
    new: Recently added
    deprecated: Deprecated
  social:
  #   - icon: fontawesome/brands/github
  #     link: https://destrix.app/t/github
  #     name: Destrix on Github
    - icon: fontawesome/brands/twitter
      link: https://wolfite.dev/?to=twitter
      name: Wolfite on Twitter
    - icon: fontawesome/brands/discord
      link: https://wolfite.dev/?to=discord
      name: Wolfite on Discord
    - icon: fontawesome/solid/link
      link: https://wolfite.dev/
      name: Wolfite on Twitter
  #   - icon: fontawesome/brands/trello
  #     link: https://destrix.app/t/trello
  #     name: Destrix on Trello
  #   - icon: fontawesome/brands/youtube
  #     link: https://destrix.app/t/youtube
  #     name: Destrix on YouTube
  #   - icon: fontaweseome/brands/twitter
  #     link: https://destrix.app/t/patreon
  #     name: Wolfite on Patreon
  # alternate:
  #   - name: English
  #     link: https://docs.destrix.app/
  #     lang: en
    # - name: Español
    #   link: https://es.docs.destrix.app/?from=lang_en
    #   lang: es
    # - name: 日本語
    #   link: https://jp.docs.destrix.app/?from=lang_en
    #   lang: jp

theme:
  name: material
  logo: https://cdn.wolfite.net/branding/wolfite/wolfite.png
  favicon: https://cdn.wolfite.net/branding/wolfite/wolfite.png
  language: en

  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - content.code.copy
    - content.action.view
    - content.tooltips
    - content.code.annotate
    - navigation.footer
    - content.tabs.link
    - search.suggest
    - search.share
    - announce.dismiss
    - toc.follow
    - navigation.indexes

  palette:

    - media: "(prefers-color-scheme)"
      primary: black
      accent: blue
      toggle:
        icon: material/link
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: black
      accent: blue
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: blue
      toggle:
        icon: material/weather-night
        name: Switch to system preference