site_name: Wolfite Documentation

markdown_extensions:
    - pymdownx.highlight:
        anchor_linenums: true
        line_spans: __span
        pygments_lang_class: true
        auto_title: false
        linenums: true
        anchor_linenums: true
    - pymdownx.keys
    - pymdownx.emoji:
        emoji_index: !!python/name:material.extensions.emoji.twemoji
        emoji_generator: !!python/name:material.extensions.emoji.to_svg
        # options:
        #   custom_icons:
        #     - overrides/.icons
    - pymdownx.inlinehilite
    - pymdownx.snippets
    - pymdownx.superfences
    - abbr
    - md_in_html
    - attr_list
    - pymdownx.snippets


nav:
  - Home: index.md
  # - WXRoblox:
  #   - wxroblox
  # - Hydrogen:
  #   - hydrogen

extra_css:
  - stylesheets/extra.css


extra:
  homepage: /
  status:
    new: Recently added
    deprecated: Deprecated
  # social:
  #   - icon: fontawesome/brands/github
  #     link: https://destrix.app/t/github
  #     name: Destrix on Github
  #   - icon: fontawesome/brands/twitter
  #     link: https://destrix.app/t/twitter
  #     name: Destrix on Twitter
  #   - icon: fontawesome/brands/discord
  #     link: https://destrix.app/t/discord
  #     name: Destrix on Discord
  #   - icon: fontawesome/brands/trello
  #     link: https://destrix.app/t/trello
  #     name: Destrix on Trello
  #   - icon: fontawesome/brands/youtube
  #     link: https://destrix.app/t/youtube
  #     name: Destrix on YouTube
  #   - icon: fontaweseome/brands/twitter
  #     link: https://destrix.app/t/patreon
  #     name: Wolfite on Patreon
  # alternate:
  #   - name: English
  #     link: https://docs.destrix.app/
  #     lang: en
    # - name: Español
    #   link: https://es.docs.destrix.app/?from=lang_en
    #   lang: es
    # - name: 日本語
    #   link: https://jp.docs.destrix.app/?from=lang_en
    #   lang: jp
copyright: >
  Copyright &copy; 2023 - 2024 <a href="//wolfite.dev?to=twitter">@Wolfite_</a>
#<br><a href="#__consent">Change cookie settings</a>

# plugins:
#   - projects:
#       projects_dir: projects
#       hoisting: false

theme:
  name: material
  logo: https://wwstatic.com/ss1/branding/wolfite/v3/clean/svg/WolfiteW.svg
  favicon: https://wwstatic.com/ss1/branding/wolfite/v3/clean/svg/WolfiteW.svg
  language: en
  # custom_dir: overrides

  

  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - content.code.copy
    - content.action.view
    - content.tooltips
    - content.code.annotate
    - navigation.footer
    - content.tabs.link
    - search.suggest
    - search.share
    - announce.dismiss
    - toc.follow
    - navigation.indexes
    # - toc.integrate
  # icon:
  #   repo: destrix/logo
  #   annotation: material/plus-circle

  
  
  palette:

    - media: "(prefers-color-scheme)"
      primary: custom
      accent: blue
      toggle:
        icon: material/link
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: custom
      accent: blue
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: void
      primary: custom
      accent: blue
      toggle:
        icon: material/weather-night
        name: Switch to system preference